### ISSUE TITLE
ModuleNotFoundError: No module named 'helper'

### ISSUE THREAD

**Issue by Jbwasse2** [alexandroid000/particle-sim#1]
I believe you have a folder named "helper" that isn't pushed. Or it isn't documented what 'helper' is.

> Traceback (most recent call last):
  File "run_sim.py", line 12, in <module>
    from backend import *
  File "/home/justin/Documents/self-assembly/ParticleSimulator/backend.py", line 9, in <module>
    from helper.shoot_ray_helper import IsInPoly, ClosestPtAlongRay
ModuleNotFoundError: No module named 'helper'

**Comment by Jbwasse2** [comment]
Figured it out, I didn't clone the submodule.
