### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'policy5.txt'

### ISSUE THREAD

**Issue by Jbwasse2** [alexandroid000/particle-sim#3]
On fresh clone I get this error, I think you just need to change permission of open to allow for creating file if its not there.

**Comment by Jbwasse2** [comment]
Note: It might be better to do these bug fixes after the April 8th deadline.

Is it required to have this policy5 file? If not, I changed
```
    policy = []
    with open("policy5.txt", 'r') as p:
        line = p.readline().strip().strip('()').split(", ")
        policy = [int(p) for p in line]

```
to
```
    # IF available,
    # load policy from file (for 5-agent MDP solution)
    policy = []
    policy_file = "policy5.txt"
    try:
        p = open(policy_file,'r')
        line = p.readline().strip().strip('()').split(", ")
        policy = [int(p) for p in line]
        p.close()
    except IOError:
        # File not found, skip importing policy
        pass
```

But this causes an error later
```
(snakes37) justin@justin-P35V6:~/Documents/forked_particles$ python run_sim.py 0 0  
Joint state= 982  
policy= []  
Traceback (most recent call last):
  File "run_sim.py", line 152, in <module>
    simulation.run(T-1)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/atooms/simulation/core.py", line 368, in run
    self.run_until(next_step)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/atooms/simulation/core.py", line 296, in run_until
    self.backend.run(steps - self.current_step)
  File "/home/justin/Documents/forked_particles/backend.py", line 174, in run
    new_orientations = decode_policy(self.policy[joint_state])
IndexError: list index out of range
```
Which looks like its from
```
for i in range(steps):
    # log regions; only works at beginning of loop for some reason
    self.log_data(i, region_counts)
    joint_state = encodeJointState(states)
    print("Joint state=",joint_state)
    print("policy=",self.policy)
    new_orientations = decode_policy(self.policy[joint_state])
```

**Comment by alexandroid000** [comment]
Removed hardcoded dependency on policy.
