### ISSUE TITLE
ValueError: Invalid file object: <_io.BufferedReader name=11>

### ISSUE THREAD

**Issue by Jbwasse2** [alexandroid000/particle-sim#4]
(snakes37) justin@justin-P35V6:~/Documents/particle-sim$ python run_sim.py 0 0
ran sim for  100 steps
wrote data to octagon_N10_T100_R0_A0.xyz
wrote data to octagon_N10_T100_R0_A0_regions.csv
writing video to octagon_N10_T100_R0_A0.mp4
Traceback (most recent call last):
  File "run_sim.py", line 165, in <module>
    mkAnimation()
  File "run_sim.py", line 110, in mkAnimation
    ani.save(simname+'.mp4', fps=15, extra_args=['-vcodec', 'libx264'])
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/matplotlib/animation.
    writer.grab_frame(**savefig_kwargs)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/contextlib.py", line 130, in __exit
    self.gen.throw(type, value, traceback)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/matplotlib/animation.
    self.finish()
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/matplotlib/animation.
    self.cleanup()
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/site-packages/matplotlib/animation.
    out, err = self._proc.communicate()
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/subprocess.py", line 939, in commun
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/subprocess.py", line 1672, in _comm
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/selectors.py", line 352, in registe
    key = super().register(fileobj, events, data)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/selectors.py", line 238, in registe
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/selectors.py", line 225, in _fileob
    return _fileobj_to_fd(fileobj)
  File "/home/justin/anaconda3/envs/snakes37/lib/python3.7/selectors.py", line 40, in _fileobj
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=11>

**Comment by Jbwasse2** [comment]
This is not a fresh clone. Closing.
